### ISSUE TITLE
[Question] Can you provide image caption of twitter15/17, snap, wikidiverse, mnre.

### ISSUE THREAD

**Issue by Chenfeng1271** [modelscope/AdaSeq#13]
### What is your question?

Hi, I notice the dataset used in MoRe does not contain the image caption of its original images. For example, twitter15 only has text, and twitter15-img and twitter15-txt have retrieved content, instead of their original image caption.  Can you provide it? Thank you.  

### What have you tried?

None

### What's your environment?

- AdaSeq Version (e.g., 1.0 or master):
- ModelScope Version (e.g., 1.0 or master):
- PyTorch Version (e.g., 1.12.1):
- OS (e.g., Ubuntu 20.04):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- Any other relevant information:

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caijiong** [comment]
I'm sorry, we don't have the image caption since the original datasets do not have captions.
