### ISSUE TITLE
Question on EMNLP22: Named Entity and Relation Extraction with Multi-Modal Retrieval

### ISSUE THREAD

**Issue by Hyusheng** [modelscope/AdaSeq#6]
### What is your question?

Thanks for your work on EMNLP22: Named Entity and Relation Extraction with Multi-Modal Retrieval.

However, your readme file does not provide environment information, such as the version of the modelscope.

Could you please clarify the specific operating environment and precautions? 

The current code seems unable to load the xlm-roberta-large model.

### What have you tried?

I read the relevant files of modelscope in https://www.modelscope.cn/docs/环境安装, but still cannot determine the reason why the xlm-roberta-large model cannot be loaded.

In addition, your repo lacks MoE code, could you please add it? Thanks.

### Code (if necessary)

- ERROR - modelscope - Authentication token does not exist, failed to access model xlm-roberta-large which may not exist or may be private. Please login first.

RuntimeError: Try loading from huggingface and modelscope failed 

modelscope: 404 Client Error: Not Found for url: http://www.modelscope.cn/api/v1/models/xlm-roberta-large/revisions?EndTime=1670428800

### What's your environment?

- AdaSeq Version (master):
- modelscope==1.1.1
- torch==1.13.1
- OS Ubuntu 20.04.5
- Python version: 3.9.13
- CUDA Version: 12.0 
- GPU models: 3090

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by izhx** [comment]
This seems to be a network problem.
`adaseq` will first try to load `xlm-roberta-large` from huggingface, if failed (here in your case may be network timeout), it will then try modelscope, where modelscope have no `xlm-roberta-large`.

You could manually download `xlm-roberta-large` files to your local dir, and replace all `xlm-roberta-large` with `path_to/xlm-roberta-large` (your local path to `xlm-roberta-large`) in config files.

**Comment by caijiong** [comment]
We appreciate your interest in our work and will release the code of MoE and related data files in the next week.

**Comment by zhiweihu1103** [comment]
> 

Hi, @caijiong . I can't seem to find the code for the MoE part, can you tell me?

**Comment by 1223243** [comment]
> > 
> 
> 嗨， .我似乎找不到 MoE 部分的代码，你能告诉我吗？

请问你现在找到了吗，我也没有找到
