### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by sangeethn** [modelscope/AdaSeq#9]
### What is your question?

Hello Team,
I am using your dataset for the competition of Multiconer problem. Many thanks to make the dataset public. Could you please upload the external sentence of test dataset as well?

### What's your environment?

- AdaSeq Version (e.g., 1.0 or master):
- ModelScope Version (e.g., 1.0 or master):
- PyTorch Version (e.g., 1.12.1):
- OS (e.g., Ubuntu 20.04):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- Any other relevant information:

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by huangshenno1** [comment]
Hello, @sangeethn. We are currently doing our best to produce the retrieval augmented sentences for test dataset, which is going to be uploaded late today. We will inform you ASAP when it's available.

**Comment by huangshenno1** [comment]
@sangeethn test datasets with external augmented sentences is now available!
See https://modelscope.cn/datasets/pangda/multico_ner_2023_wiki128

If you are using any config file from the example, no modifications on the config is needed. But you should clear your data cache in ~/.modelscope to ensure running with new test data.

**Comment by sangeethn** [comment]
Thank you very much..
